spring:
  application:
    name: rest-movie
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      file: ./rest-movie/compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: postgres
    hikari:
      pool-name: movie-hikiari-pool
      maximum-pool-size: 10
      auto-commit: false
      connection-init-sql: SELECT 1
      leak-detection-threshold: 3000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      #javax.persistence.schema-generation.scripts.action: create
      #javax.persistence.schema-generation.scripts.create-target: rest-movie/src/main/resources/db/migration/V1__initial_schema.sql
      hibernate.format_sql: true
      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
# Vaadin
vaadin:
  launch-browser: true
# Logging
logging:
  level:
    org.hibernate.session.metrics: DEBUG
    com.zaxxer.hikari: DEBUG