spring:
  application:
    name: rest-movie
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      file: ./rest-movie/compose.yaml
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: postgres
    hikari:
      pool-name: movie-hikiari-pool
      maximum-pool-size: 10
      auto-commit: false
      leak-detection-threshold: 3000
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate.format_sql: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.fetch_size: 50
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    table: movie_flyway_schema_history
# JobRunr
jobrunr:
  background-job-server:
    enabled: true
    name: ${spring.application.name}-jobrunr
    thread-type: virtualthreads
  job-scheduler:
    enabled: true
  database:
    table-prefix: movie_
  dashboard:
    enabled: true
    port: 8000
# Vaadin
vaadin:
  launch-browser: false
# Springdoc
springdoc:
  swagger-ui:
    enabled: false
  show-actuator: false
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health"
# Logging
logging:
  level:
    org.hibernate.session.metrics: INFO
    com.zaxxer.hikari: INFO