spring:
  application:
    name: rest-movie
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      file: ./rest-movie/compose.yaml
  datasource:
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
vaadin:
  launch-browser: true